### ISSUE TITLE
command not found, on line 206

### ISSUE THREAD

**Issue by greytear** [yoselita/aerosols4wrf#1]
Having NCL,nco and cdo available, suggested user to comment line 66, but we're having a "command not found" on line 206:

			coordinates = "XLONG XLAT XTIME"

**Comment by yoselita** [comment]
Thank you for reporting the error.The syntax error when declaring the bash variable `coordinates` occurred, it should not be any space after the "=" sign:

```
coordinates="XLONG XLAT XTIME"
```
This has been fixed in the code. Let us know if it works for you now.
